### ISSUE TITLE
Fatal Error: Call to a member function register_handler() on a non-object

### ISSUE THREAD

**Issue by studioromeo** [nb/wordpress-tests#1]
Not sure what i'm doing wrong. Set it all up using MAMP on default ports yet i keep getting this error:

```
Fatal error: Call to a member function register_handler() on a non-object in /../wp.3.2.1/wp-includes/media.php on line 1301
```

Has anyone got any ideas on whats going on here?

**Comment by scribu** [comment]
Same here, using Ubuntu and WP trunk.

**Comment by nb** [comment]
This should have been fixed in http://core.trac.wordpress.org/changeset/18532

It's normal to happen in 3.2.1, but not in trunk.

scribu, it all works for me in trunk. Could you share the tests and make sure you have latest trunk?

**Comment by studioromeo** [comment]
Ah!! I've been using 3.2.1 that's probably why. Thanks @nb will have a go on the trunk later & report back

**Comment by scribu** [comment]
Yep, works now. This issue can be closed.
