### ISSUE TITLE
is_email() does allow blah domain?

### ISSUE THREAD

**Issue by kayue** [nb/wordpress-tests#14]
When I ran `phpunit test_test.php`, there was 1 failure:

```
1) WP_Is_Email_Test::test_is_email_should_not_allow_blah_domain
Failed asserting that 'nb@nikolay.blahasdfasdf' is false.
```

Should this be correct?

**Comment by scribu** [comment]
`nikolay.blahasdfasdf` doesn't seem like a valid domain name to me.

Also note that these tests are mostly examples at this point. The official WP unit tests are here:

http://unit-tests.trac.wordpress.org/

**Comment by kayue** [comment]
The thing is we have the following test in `test_test.php`, which will never pass because `is_email()` will not return `false` for this email. 

```
function test_is_email_should_not_allow_blah_domain() {
    $this->assertFalse( is_email( 'nb@nikolay.blah' ) );
}
```

Should we remove this test from `test_test.php`?

**Comment by scribu** [comment]
I think it was meant as an example of how a failure looks like. As I said, these are dummy tests, so let's leave it in.

**Comment by kayue** [comment]
Oh I see. Understood.
