### ISSUE TITLE
Port convenience functions from wpcore unit-tests

### ISSUE THREAD

**Issue by paulgibbs** [nb/wordpress-tests#17]
There are a few functions in the wpcore units-tests that would be very useful in this package, as they would very probably be used by many plugins that build tests on this package. Specifically:
- WPTestCase::http (for loading different URLs)
- WPTestCase::_make_user, _destroy_user, _destroy_users
- WPXMLRPCServerTestCase::_flush_roles

If interested, I can work on this and send you a pull request, if you let me know where you'd like these put.

**Comment by scribu** [comment]
Indeed, I have a utility for creating users, so yeah, make_user() would be handy. _destroy_user(), not so much, since everything is rolled back automatically before a new test.

I think a static class would be the best place to put these, eg. `WP_Test::make_user()` etc.

**Comment by paulgibbs** [comment]
http() has already been copied in, it is called WP_UnitTestCase::go_to(). Do you want these others in WP_UnitTestCase?

**Comment by scribu** [comment]
Since they aren't related to any specific test case, I don't think they should be part of the test case class.

**Comment by nb** [comment]
I would very much prefer to port the factories from GlotPress. This way we will:
- have unified interface for creating any object
- allows us not to specify data we don't care about
- it also gives a namespace to put more specific creation methods

Examples:

``` php
// creates user for which we don't care about any of the attributes
$user = $this->factory->user->create();
// creates a user with specific username, if we need to test some username functionality
$user = $this->factory->user->create( array( 'user_login' => 'baba' ) );
// here we can add specific creation methods
$admin_user = $this->factory->user->create_admin();
// this way it can work for the rest of the entities
$post = $this->factory->post->create();
```

I added a reference to test object mostly for convenience.

**Comment by nb** [comment]
For deleting users, we should have such a function in core.

**Comment by scribu** [comment]
> I would very much prefer to port the factories from GlotPress.

+1

**Comment by maxcutler** [comment]
I've made a start on this in my [branch](https://github.com/maxcutler/wordpress-tests/blob/master/lib/factory.php). It's far from finished and will be refined further as I port over more of the unit tests. Feedback/forks/pull-requests would be appreciated.

**Comment by scribu** [comment]
It would be nice if you isolated the commits for this into a branch and opened a pull request.

There already are a couple of fork branches that do all sorts of things (and are therefore hard to merge).

**Comment by maxcutler** [comment]
@scribu: Broke the factory work out into a separate branch and submitted it as a pull request.

**Comment by scribu** [comment]
For reference: #22

**Comment by scribu** [comment]
This framework was ported to unit-tests.trac instead, so the issue is moot.
