### ISSUE TITLE
Changing the configuration to MultiSite doesn't trigger reinstall

### ISSUE THREAD

**Issue by gcorne** [nb/wordpress-tests#23]
When testing both normal and MultiSite installations, changing  WP_ALLOW_MULTISITE in the configuration doesn't trigger a reinstall.

**Comment by scribu** [comment]
That's going to be tricky to detect.

**Comment by gcorne** [comment]
The version file could contain a sha1 hash of several parameters instead of using just the db_version.

**Comment by scribu** [comment]
That makes sense. Care to open a pull request?

**Comment by scribu** [comment]
Merged pull request. Thanks, gcorne.
