### ISSUE TITLE
Possible Issue With Permalinks?

### ISSUE THREAD

**Issue by cordulack** [nb/wordpress-tests#6]
My apologies if this is a user issue and not an issue with the tests.  Everything works great on a WordPress install set up with default permalinks, but switching the permalink format to include the post name instead of the post ID results in an error when running the test suite.  The error I am getting is: 

Fatal error: Call to a member function add_rewrite_tag() on a non-object in /Applications/MAMP/htdocs/clean-wp-install/wp-includes/taxonomy.php on line 333

**Comment by scribu** [comment]
This should no longer be a problem. See #1
